### ISSUE TITLE
[Bug]: Generating helper files get stuck at Eloquent

### ISSUE THREAD

**Issue by MightyPork** [laravel-idea/plugin#1041]
### Bug description

![Screenshot_20240730_094422](https://github.com/user-attachments/assets/1baeaead-9a75-481f-b506-6f9b4337e1a2)

### Plugin version

8.2.2.241

### Operating system

Linux

### Relevant log output

```shell
There isn't any error or warning in the log file, it just gets stuck
```

**Comment by adelf** [comment]
It's hard to make any clues here. I'm working on some optimizations of helper code generation right now. Let's wait the next update, which should be released this week, and see if it helps?

**Comment by MightyPork** [comment]
It is reliably reproducible for me on this project, on two different computers. Maybe I can get you some debug info if you tell me how.

Here's a piece of log (the big error was when I clicked the Generate helper code button while index was building. That's not related to it never finishing the eloquent code.

```
2024-08-06 00:44:17,011 [ 104338]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.util.indexing.DumbModeWhileScanningTrigger$DumbModeWhileScanning@6293f1b9
2024-08-06 00:44:17,011 [ 104338]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[flowbox-laravel, 1 iterators, reason: changes in: "External roots from entity (empty; empty; phpstan.phar, phpstan.phar; empty)"]
2024-08-06 00:44:17,012 [ 104339]   INFO - #c.i.u.i.c.IndexUpdateRunner - Using 7 indexing and 4 writing threads for indexing
2024-08-06 00:44:21,129 [ 108456]   INFO - #c.i.o.a.i.ActionManagerImpl - Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:843)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:791)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:148)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:838)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:134)
	at com.laravel_idea.plugin.common.d.a.a(a.java:42)
	at com.laravel_idea.plugin.helperCodeGeneration.a.d.a(d.java:45)
	at com.laravel_idea.plugin.helperCodeGeneration.a.f.a(f.java:21)
	at com.laravel_idea.plugin.helperCodeGeneration.k.a(k.java:20)
	at com.laravel_idea.plugin.helperCodeGeneration.HelperCodeGeneration$b$a.a(HelperCodeGeneration$b$a.java:163)
	at com.laravel_idea.plugin.helperCodeGeneration.HelperCodeGeneration$b$a.invoke(HelperCodeGeneration$b$a.java:162)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at com.laravel_idea.plugin.helperCodeGeneration.HelperCodeGeneration$b.a(HelperCodeGeneration$b.java:162)
	at com.laravel_idea.plugin.helperCodeGeneration.HelperCodeGeneration$b.compute(HelperCodeGeneration$b.java:153)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:394)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:86)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-08-06 00:44:25,730 [ 113057]   INFO - #c.i.u.i.ProjectChangedFilesScanner - Retrieving changed during indexing files of flowbox-laravel : 0 to update, calculated in 0ms
2024-08-06 00:44:25,750 [ 113077]   INFO - #c.i.u.i.UnindexedFilesIndexer - Finished for flowbox-laravel. Unindexed files update took 8738ms; general responsiveness: ok; EDT responsiveness: ok
2024-08-06 00:44:25,751 [ 113078]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) UnindexedFilesIndexer[flowbox-laravel, 1 iterators, reason: changes in: "External roots from entity (empty; empty; phpstan.phar, phpstan.phar; empty)"]
2024-08-06 00:44:25,753 [ 113080]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [flowbox-laravel]
2024-08-06 00:44:25,852 [ 113179]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - Indexing 14239 commits in flowbox
2024-08-06 00:44:28,239 [ 115566]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - 2.384s for indexing 14239 new commits out of 14239 in flowbox
2024-08-06 00:44:28,428 [ 115755]   INFO - #c.i.v.l.d.i.IndexDiagnosticRunner - Index diagnostic for 29 commits in [file:///srv/flowbox] is completed
2024-08-06 00:44:28,455 [ 115782]   WARN - #c.j.p.PhpIndex - Completing type '#M#C\Illuminate\Support\Collection.map' took 617ms, visited:[#M#C\Illuminate\Support\Collection.map]
2024-08-06 00:44:28,497 [ 115824]   WARN - #c.j.p.PhpIndex - Invalid Signature '\Illuminate\Support\Collection<#ᢐ\TKey.,#ᢐ\TMapValue.>'
2024-08-06 00:44:29,604 [ 116931]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.psi.css.impl.util.CssReferenceProvider <clinit> requests org.intellij.images.fileTypes.ImageFileTypeManager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
2024-08-06 00:45:26,661 [ 173988]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-08-06 00:45:26,661 [ 173988]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-08-06 00:45:59,088 [ 206415]   WARN - #c.i.u.x.Binding - No accessors for com.intellij.toolWindow.ToolWindowLayoutStorageManagerState. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-08-06 00:46:02,700 [ 210027]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-08-06 00:46:02,700 [ 210027]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
```

**Comment by adelf** [comment]
Have you tried the main menu > File > Invalidate Caches?

**Comment by MightyPork** [comment]
I think I found the problem. It was just taking extremely long time, because it indexed files outside the models folder.

We have a folder with helper files for IDE type hinting that look like this:

```php
<?php
namespace Cty;

/**
 * @property bool $status_ok - Not error or alarm
 * @property bool $error - Error state
 * @property bool $alarm - Alarm state
 * @property array $errors - Errors list
 * @property array $alarms - Alarms list
 * .....
 */
class ACS550 extends \App\Models\Component {}
```

There are over 600 of them. The plugin indexed them as if they were real models.

**Comment by adelf** [comment]
Does \App\Models\Component extend Eloquent Model class?

**Comment by MightyPork** [comment]
It does, well we use a custom `BaseModel` class and it extends `\MongoDB\Laravel\Eloquent\Model` which in turn extends `Illuminate\Database\Eloquent\Model`

 I suppose this will need some way to blacklist a folder or indicate to the plugin that these are not models.

**Comment by adelf** [comment]
Will it be ok to blacklist some namespace?

**Comment by MightyPork** [comment]
sure, "Cty" is not even registered in composer.json, it's just sitting in the app folder for phpstorm to find it.

We then use it like this

```
/** @var \Cty\ACS550 $comp */
```

or in type hints as `Component|\Cty\ACS550`, which feels icky but works.

the whole thing is because the models are polymorphic in mongodb

**Comment by adelf** [comment]
Could you add the `ide.json` file to your project with this content?

```json
{
    "$schema": "https://laravel-ide.com/schema/laravel-ide-v2.json",
    "helperCode": {
        "eloquent": {
            "ignoreNamespaces": ["Cty"]
        }
    }
}
```

**Comment by MightyPork** [comment]
That fixed it! Thank you

But I get a notification with many Table not found warnings. It found all mysql tables (explicit `$connection = 'mysql'` in the model), but none mongodb ones (default connection "mongodb")

**Comment by adelf** [comment]
Laravel Idea can't find MongoDB tables. Usually it analyzes migration files and tries to find Schema::create() and other DDL calls there. How do you define your Mongo tables?

**Comment by MightyPork** [comment]
Yeah they are in migrations, but if you depend on it being called Schema::create, that explains it. We're bending things a little. It's fine, I'm not actually sure what these helper files were intended to do.

```php
return new class () extends BaseMigration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::createIfNotExist('logic_log', function (Blueprint $table) {});
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::dropIfExists('logic_log');
    }
};
```

It's a non-standard function we add with patch files. 

```php
	public function createIfNotExist($collection, Closure $callback = null)
	{
		if (!$this->hasCollection($collection)) {
			$this->create($collection, $callback);
		}
	}
```

The problem is that mongodb collections are created automatically when accessed, so during upgrade, if something touched the collection, then `Schema::create` would crash.

**Comment by adelf** [comment]
`Schema::createIfNotExist('logic_log', function (Blueprint $table) {});`

What is inside this lambda? Mostly the typical field declarations?

**Comment by MightyPork** [comment]
There's nothing, it's empty. I only omitted the use block, otherwise the file is verbatim copied from the project.

Mongodb fields are not declared, we only use these migrations out of habit, I guess. The only thing that can be there afaik is defining indexes.

The fields ("columns") are declared using @property tags on the model class.
