### ISSUE TITLE
Non-idempotent computation: it returns different results when invoked multiple times or on different threads:   2 != 4

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel-idea/plugin#262]
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  2 != 4
  which is length of [com.phpuaca.reference.StringReference@43ef8443, com.laravel_idea.plugin.eloquent.f.f@4aca3788] and [com.phpuaca.reference.StringReference@a0d21c4, dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'from':(1,5)), dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'from':(1,5)), com.laravel_idea.plugin.eloquent.f.f@c1f20a]

Recomputation gives com.intellij.util.CachedValueBase$Data@54f4c83b which is different from both values
Recomputation log:
  com.phpuaca.reference.StringReferenceProvider@3fb3b3cd returned [com.phpuaca.reference.StringReference@24deb5c4]
  dev.ekvedaras.laravelquery.reference.ColumnReferenceProvider@3b4e4fd3 returned [dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'from':(1,5))]
  com.laravel_idea.plugin.a.d@9de1943 returned [com.laravel_idea.plugin.eloquent.f.f@43325edd]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:165)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:88)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:75)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:432)
	at com.laravel_idea.plugin.extension.inspections.LaravelDeprecatedRoutesInspection$buildVisitor$1.visitPhpStringLiteralExpression(LaravelDeprecatedRoutesInspection.kt:32)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:36)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:270)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:268)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:268)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by adelf** [comment]
It looks like some compatibility issue between 3 plugins: Laravel Idea, Laravel Query and PHPUnit Autocomplete Assistant. Could you tell the PhpStorm version and plugin versions?

**Comment by CrazyBoy49z** [comment]
![image](https://user-images.githubusercontent.com/3448603/113360418-6e2d5c80-9352-11eb-83ed-72c11ebd1cc3.png)
![image](https://user-images.githubusercontent.com/3448603/113360450-81402c80-9352-11eb-9242-a8de8d6e1d2f.png)
![image](https://user-images.githubusercontent.com/3448603/113360462-89986780-9352-11eb-8855-242968ca8ec1.png)
Как понимаю 3 плагин это 
![image](https://user-images.githubusercontent.com/3448603/113360544-afbe0780-9352-11eb-9037-59c5f409aa34.png)

**Comment by adelf** [comment]
It's fixed in the 4.3.1 version but can appear in some other cases. The "Laravel Query" plugin makes references a bit incorrectly.
