### ISSUE TITLE
Exception after PHP storm Update to 2021.1 with laravel_idea.plugin (4.2.1.211)

### ISSUE THREAD

**Issue by Mohmdthabet** [laravel-idea/plugin#268]
Please find the error log and phpstorm details

java.lang.StackOverflowError
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:618)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:952)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:314)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:647)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:624)
	at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:547)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.isInForeignFunction(ClassReferenceImpl.java:271)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:236)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:228)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:345)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:391)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:418)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:409)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:403)
	at com.laravel_idea.plugin.eloquent.m.a(m.java:61)
	at com.laravel_idea.plugin.eloquent.m.a(m.java:65)
	at com.laravel_idea.plugin.eloquent.m.a(m.java:65)
	at com.laravel_idea.plugin.eloquent.m.a(m.java:65)

PHPStorm version:

PhpStorm 2021.1
Build #PS-211.6693.120, built on April 7, 2021

Registry: run.processes.with.pty=TRUE,
 debugger.mayBringFrameToFrontOnBreakpoint=false,
 ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation (8.14.203.000.0), 
com.github.mturlo.intellij.theme.spacegray (1.4.1),
 com.intellij.javafx (1.0.3), com.jfboily.darkjeff (1.1),
 com.vecheslav.darculaDarkerTheme (1.2.0), 
com.xinkun.theme.md (1.7.12), 
myBitbucket (0.4), 
mobi.hsz.idea.gitignore (4.0.4),
 com.laravel_idea.tailwind (1.3.0),
 com.dmarcotte.handlebars (211.6693.44), 
com.aurimasniekis.phppsr4namespacedetector (1.0.1), 
com.github.ArtsiomCh.NestedBracketsColorer (0.5.0), 
de.espend.idea.laravel (0.15.4),
 dev.nybroe.collector (0.3.2),
 de.espend.idea.php.toolbox (5.1.1),
 de.espend.idea.php.annotation (8.0.0),
 fr.adrienbrault.idea.symfony2plugin (0.22.206),
 ru.adelf.idea.dotenv (2021.1), 
com.laravel_idea.plugin (4.2.1.211)

**Comment by adelf** [comment]
Fixed. Thank you, Mohamed.

**Comment by adelf** [comment]
Laravel Idea 4.2.2 is out.
