### ISSUE TITLE
Exception occurs when editing a migration

### ISSUE THREAD

**Issue by rk** [laravel-idea/plugin#289]
So far, it's only 1 migration I've needed to edit since the last update. And it likes to throw this when I do:

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.php.lang.psi.elements.impl.MethodImpl #PHP 
invalidated at: see attachment
	at com.intellij.psi.impl.source.SubstrateRef$1.getNode(SubstrateRef.java:65)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:134)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.getNameNode(MethodImpl.java:131)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamedElementImpl.getName(PhpNamedElementImpl.java:74)
	at com.laravel_idea.plugin.misc.l.getLookupString(l.java:12)
	at com.intellij.codeInsight.lookup.LookupElement.getAllLookupStrings(LookupElement.java:43)
	at com.intellij.codeInsight.lookup.LookupElementDecorator.getAllLookupStrings(LookupElementDecorator.java:48)
	at com.intellij.codeInsight.completion.impl.CamelHumpMatcher.prefixMatchersInternal(CamelHumpMatcher.java:106)
	at com.intellij.codeInsight.completion.impl.CamelHumpMatcher.prefixMatches(CamelHumpMatcher.java:102)
	at com.intellij.codeInsight.completion.CompletionResult.wrap(CompletionResult.java:24)
	at com.intellij.codeInsight.completion.BaseCompletionService$BaseCompletionResultSet.addElement(BaseCompletionService.java:116)
	at com.intellij.codeInsight.completion.CompletionResultSet.addAllElements(CompletionResultSet.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.lambda$addAllElements$0(CompletionServiceImpl.java:102)
	at com.intellij.codeInsight.completion.CompletionThreadingBase.withBatchUpdate(CompletionThreadingBase.java:33)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addAllElements(CompletionServiceImpl.java:102)
	at com.laravel_idea.plugin.misc.m.addCompletions(m.java:42)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:60)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:133)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:41)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:863)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:574)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:162)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:859)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:847)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:353)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:345)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by adelf** [comment]
Thanks for reporting this. Could you tell the PhpStorm and Laravel Idea
versions?

**Comment by rk** [comment]
From the PHPStorm about window:

```
PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 1536M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation (8.15.203.000.2), com.alayouni.ansiHighlight (1.2.4), com.elliotwaite.cyberpunk_theme (1.0.5), com.intellij.ideolog (203.0.27.0), mobi.hsz.idea.gitignore (4.1.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), de.espend.idea.php.annotation (8.0.0), net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0), fr.adrienbrault.idea.symfony2plugin (0.23.208), ru.adelf.idea.dotenv (2021.1), com.laravel_idea.plugin (4.2.2.211), net.seesharpsoft.intellij.plugins.csv (2.16.3)
```

Laravel Idea: `com.laravel_idea.plugin (4.2.2.211)`

**Comment by adelf** [comment]
4.3.2 version is available.
