### ISSUE TITLE
Non-idempotent computation: it returns different results when invoked multiple times or on different threads:   1 != 3

### ISSUE THREAD

**Issue by workaandrey** [laravel-idea/plugin#296]
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  1 != 3
  which is length of [com.laravel_idea.plugin.eloquent.g.d@29763dcc] and [dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'position':(1,9)), dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'position':(1,9)), com.laravel_idea.plugin.eloquent.g.d@1d2e23d5]

Recomputation gives com.intellij.util.CachedValueBase$Data@5b8d4ead which is equivalent to 'fresh'
Recomputation log:
  com.jetbrains.php.lang.PhpReferenceContributor$CallbackReferenceProvider@6246cfc3 returned [com.jetbrains.php.lang.PhpCallbackReferenceBase$PhpVariableCallbackReference(StringLiteralExpressionImpl: 'diplomas':null)]
  com.jetbrains.php.lang.PhpReferenceContributor$CallbackReferenceProvider@6246cfc3 returned [com.jetbrains.php.lang.PhpCallbackReferenceBase$PhpVariableCallbackReference(StringLiteralExpressionImpl: 'diplomas':null)]
  dev.ekvedaras.laravelquery.reference.ColumnReferenceProvider@1145d5a9 returned [dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'position':(1,9)), dev.ekvedaras.laravelquery.reference.ColumnPsiReference(StringLiteralExpressionImpl: 'position':(1,9))]
  com.laravel_idea.plugin.e.d@528c8fcf returned [com.laravel_idea.plugin.eloquent.g.d@fe1a045]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:432)
	at com.laravel_idea.plugin.extension.inspections.LaravelDeprecatedRoutesInspection$buildVisitor$1.visitPhpStringLiteralExpression(LaravelDeprecatedRoutesInspection.kt:32)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:36)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by adelf** [comment]
It's a problem in the "Laravel Query" plugin... I'll try to suppress this exception, or make a PR to this plugin.

**Comment by ekvedaras** [comment]
Working on it!

**Comment by adelf** [comment]
Fixed by Laravel Query plugin v2.0.3.
