### ISSUE TITLE
Exception in plugin Laravel Idea 4.2.2.211

### ISSUE THREAD

**Issue by mertasan** [laravel-idea/plugin#299]
Following exceptions happened soon after this one, most probably they are induced.

```java
java.lang.StackOverflowError
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.get(ResolveCache.java:110)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:226)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.multiResolve(VariableImpl.java:385)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.resolve(VariableImpl.java:344)
	at com.laravel_idea.plugin.blade.livewire.a.a.a(a.java:43)
	at com.laravel_idea.plugin.blade.livewire.a.a.b(a.java:36)
	at com.laravel_idea.plugin.blade.livewire.a.a.b(a.java:36)
	at com.laravel_idea.plugin.blade.livewire.a.a.b(a.java:36)
	at com.laravel_idea.plugin.blade.livewire.a.a.b(a.java:36)
        ...
        ...
        ...
        ...
```

**Comment by adelf** [comment]
Fixed. Thanks.

**Comment by adelf** [comment]
4.3 is released
