### ISSUE TITLE
[Bug]: java.lang.StringIndexOutOfBoundsException / broken highlighting

### ISSUE THREAD

**Issue by mylemans** [laravel-idea/plugin#426]
### Bug description

I updated PhpStorm and Laravel Idea to both its latest version (2021.2.3 and 4.4.2.212) and keep getting the same exception multiple times.

As a result (or so it seems) highlighting breaks mid-code.

![Screenshot 2021-10-15 at 15 48 37](https://user-images.githubusercontent.com/749261/137498550-2c7061ed-01a4-45bb-a882-2f1be398a54b.jpg)

Note: In the screenshot the highlighting issue seems to be gone now, but I saw it before. When it happened, 'setEndCreationDate' wasn't properly colored (it was white) but as mentioned lower, I have seen much larger sections not being highlighted properly.

edit: Better screenshot showing the 'effect' the exception has (imho):

![better example](https://user-images.githubusercontent.com/749261/137499216-2cec5997-f503-4064-9627-1f74f942ea9e.jpg)

I tried to reindex all + restart the editor, but its then when it triggers (when I restart phpstorm, it now loads up the file from that screenshot and even more stuff is 'white' now vs colored + I get said exception, 'clicking through' still works + 'intellisense' stuff like route still works too)

### Plugin version

4.4.2.212

### Operating system

MacOS

### Steps to reproduce

For me, I had to restart the editor with open files and wait a very short while. The active file would load with broken highlighting (only partially 'colored').

### Relevant log output

```shell
java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.laravel_idea.plugin.eloquent.f.b.getBySignature(b.java:46)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:776)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:649)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:113)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.getExtendedClassesToSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:89)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.complete(PhpGenericsBaseExtendedWithGenericTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:158)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:158)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:237)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:757)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.lambda$getTarget$13(PhpParameterBasedTypeProvider.java:452)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getTarget(PhpParameterBasedTypeProvider.java:452)
	at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getBySignature(PhpParameterBasedTypeProvider.java:267)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:776)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:649)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:113)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.getExtendedClassesToSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:89)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.complete(PhpGenericsBaseExtendedWithGenericTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:158)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:158)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:237)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:757)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at de.espend.idea.php.toolbox.type.PhpToolboxTypeProvider.getBySignature(PhpToolboxTypeProvider.java:99)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:782)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:171)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:94)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:688)
	at com.jetbrains.php.lang.psi.elements.PhpTypedElement.getGlobalType(PhpTypedElement.java:58)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:47)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpMethodReference(PhpVoidFunctionResultUsedInspection.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:353)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:353)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by adelf** [comment]
Fixed. Thank you.

**Comment by adelf** [comment]
4.4.3 version with fix is released this week.
