### ISSUE TITLE
[Bug]: com.intellij.util.IncorrectOperationException: Cannot modify a read-only directory

### ISSUE THREAD

**Issue by AbdelrahmanMohamedDesoky** [laravel-idea/plugin#427]
### Bug description

I didn't even open Laravel Idea, I just look often at the bottom right corner of my IDE and notice that an exception has occurred with Laravel Idea.

Here are PHPStorm versions and active plugins.
```
PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
Licensed to Abdelrahman Mohamed
Subscription is active until May 25, 2022.
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-89-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, debugger.watches.in.variables=false, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: org.sonarlint.idea (6.0.0.37696), com.intellij.properties (212.4746.57), org.pydemia.theme.cobalt9 (1.1.8), Key Promoter X (2021.2), github.cweijan.test-theme (1.6), ColorIde (2.3), com.intellij.plugins.vscodekeymap (212.3116.29), com.markskelton.one-dark-theme (5.4.0), mobi.hsz.idea.gitignore (4.2.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), de.espend.idea.php.annotation (8.0.0), de.espend.idea.laravel (0.15.4), com.vexus2.cakestorm (0.6.1), ru.adelf.idea.dotenv (2021.3.0.212), com.laravel_idea.plugin (4.4.2.212), lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002)
Current Desktop: GNOME
```

I have also added the stacktrace.txt in the "Relevant log output" section of the bug report.

If you need any more details or info, I'd be glad to provide them and reply as soon as possible.

### Plugin version

4.4.2.212

### Operating system

Linux

### Steps to reproduce

Honestly, I have no idea how to reproduce this as all I do Is just open the IDE and wait till it happens, even without interacting with Laravel Idea at all.

### Relevant log output

```shell
com.intellij.util.IncorrectOperationException: Cannot modify a read-only directory '/home/desoky/Izam/izam-daftra/laravel/vendor'.
	at com.intellij.psi.impl.CheckUtil.checkWritable(CheckUtil.java:22)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.checkCreateSubdirectory(PsiDirectoryImpl.java:314)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.createSubdirectory(PsiDirectoryImpl.java:295)
	at com.laravel_idea.plugin.psi.helpers.c.a(c.java:17)
	at com.laravel_idea.plugin.helperCodeGeneration.b.a.a(a.java:68)
	at com.laravel_idea.plugin.helperCodeGeneration.f$e$a$b.run(f$e$a$b.java:70)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.laravel_idea.plugin.common.g$a.run(g$a.java:9)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.laravel_idea.plugin.common.g.a(g.java:8)
	at com.laravel_idea.plugin.helperCodeGeneration.f$e$a.run(f$e$a.java:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adelf** [comment]
Laravel Idea now shows a message "directory is read-only". Thank you for reporting.
