### ISSUE TITLE
[Bug]: fail to generate form request in modular project 

### ISSUE THREAD

**Issue by ibrahem-kamal** [laravel-idea/plugin#451]
### Bug description

as the title says , i am trying to generate a form request using the modular project , what i did 

i choosed the module from the dropdown , wrote the request name , but then it generated empty file with error 

### Plugin version

latest

### Operating system

MacOS

### Relevant log output

```shell
java.nio.file.NoSuchFileException: /Users/ibrahemkamal/Library/Application Support/JetBrains/PhpStorm2021.2/plugins/Laravel Idea/lib/laravel-idea-4.4.3.212.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1839)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at com.intellij.util.io.URLUtil.openStream(URLUtil.java:63)
	at com.intellij.ide.fileTemplates.impl.UrlUtil.loadText(UrlUtil.java:33)
	at com.intellij.ide.fileTemplates.impl.DefaultTemplate.lambda$getText$0(DefaultTemplate.java:102)
	at com.intellij.ide.fileTemplates.impl.DefaultTemplate.loadText(DefaultTemplate.java:70)
	at com.intellij.ide.fileTemplates.impl.DefaultTemplate.getText(DefaultTemplate.java:102)
	at com.intellij.ide.fileTemplates.impl.BundledFileTemplate.getDefaultText(BundledFileTemplate.java:53)
	at com.intellij.ide.fileTemplates.impl.FileTemplateBase.getText(FileTemplateBase.java:76)
	at com.intellij.ide.fileTemplates.impl.FileTemplateBase.getText(FileTemplateBase.java:98)
	at com.laravel_idea.plugin.generation.a.f.b(f.java:102)
	at com.laravel_idea.plugin.generation.a.f.a(f.java:39)
	at com.laravel_idea.plugin.generation.a.f.b(f.java:34)
	at com.laravel_idea.plugin.generation.a.h.b(h.java:15)
	at com.laravel_idea.plugin.generation.e.b$a.run(b$a.java:24)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.laravel_idea.plugin.common.f$a.run(f$a.java:12)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.laravel_idea.plugin.common.f.a(f.java:11)
	at com.laravel_idea.plugin.generation.e.b.a(b.java:22)
	at com.laravel_idea.plugin.generation.models.settings.CodeGenerationSettings.b(CodeGenerationSettings.kt:96)
	at com.laravel_idea.plugin.generation.models.settings.GenerationAction$a.run(GenerationAction$a.java:12)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
	at com.laravel_idea.plugin.generation.models.settings.GenerationAction.a(GenerationAction.kt:11)
	at com.laravel_idea.plugin.generation.e.a$b.elementChosen(a$b.java:38)
	at com.intellij.ide.util.gotoByName.ChooseByNamePopup.close(ChooseByNamePopup.java:221)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.doClose(ChooseByNameBase.java:741)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.lambda$initUI$1(ChooseByNameBase.java:595)
	at java.desktop/javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at java.desktop/javax.swing.JTextField.postActionEvent(JTextField.java:723)
	at java.desktop/javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:839)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2903)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2951)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2865)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$MyTextField.processKeyEvent(ChooseByNameBase.java:1178)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:801)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adelf** [comment]
Hello. It seems, there are some issues with Linux file rights. PhpStorm can't get a template text.

**Comment by ibrahem-kamal** [comment]
hmm, any suggest to how to debug it or fix it ?

**Comment by gorbunov** [comment]
Can't repoduce
