### ISSUE TITLE
[Bug]:  Cannot create com.laravel_idea.plugin.extension.settings.LaravelIdeaPersonalSettings because container is already disposed 

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel-idea/plugin#456]
### Bug description

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.laravel_idea.plugin.extension.settings.LaravelIdeaPersonalSettings because container is already disposed (container=Project(name=finiv, containerState=DISPOSE_COMPLETED, componentStore=/Users/macbook/projects/finiv) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:43)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:612)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.laravel_idea.plugin.extension.settings.LaravelIdeaPersonalSettings$Companion.getInstance(LaravelIdeaPersonalSettings.kt:13)
	at com.laravel_idea.plugin.helperCodeGeneration.f.c(f.java:113)
	at com.laravel_idea.plugin.helperCodeGeneration.f.e(f.java:20)
	at com.laravel_idea.plugin.extension.e.e$a$b.run(e$a$b.java:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Plugin version

4.4.4.212

### Operating system

MacOS

### Relevant log output

```shell
PhpStorm 2021.2.3
Build #PS-212.5457.49, built on October 13, 2021
Licensed to Yurij Finiv
Subscription is active until December 17, 2021.
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, run.processes.with.pty=TRUE, editor.distraction.free.mode=true, ide.experimental.ui.toolwindow.stripes=true, ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: intellij.webp (212.4746.57), com.wakatime.intellij.plugin (13.1.3), Key Promoter X (2021.3), com.github.czy211.licensetemplate (2.0.0), cc.moky.intellij.plugin.svga-support (1.0.8), com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1), com.mallowigi.imageicon (13.0), com.mnr.java.intellij.idea.plugin.base64helper (2.0.3), com.tabnine.TabNine (0.5.3), bundled-phpstorm-help (212.5457.49), in.thekalinga.snippet.intellij (6.1.0), com.intellij.jira (3.7.0), com.intellij.properties (212.4746.57), String Manipulation (8.22.203.000.1), io.aesy.regex101 (0.2), com.ultrahob.zerolength.plugin2 (0.93), com.wix.sasslint (1.1.2), com.materkey.codepoints (1.0.2), ideanginx9 (0.1.9), com.xiaobing1024.laravel (1.1.1), jones.restarteslintaction.restart-eslint-action (0.0.1), intellij.prettierJS (212.5080.8), dev.nybroe.collector (0.3.5), org.endpointdeps.EndpointDependencies (1.3), io.nimbly.json.Any2Json (2.17.3), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.5), com.alicannklc.laravel.snippets (1.1.1), nl.deschepers.laraveltinker (2.3.1), com.chrisrm.idea.MaterialThemeUI (6.9.1), net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0), ru.adelf.idea.dotenv (2021.3.0.212), com.laravel_idea.plugin (4.4.4.212), de.espend.idea.laravel (0.15.4), de.espend.idea.php.annotation (8.0.0), com.pestphp.pest-intellij (1.2.1), com.mallowigi (50.2.0), pers.fw.doc_en (1.1), izhangzhihao.rainbow.brackets (6.21), com.funivan.idea.phpClean (2021.09.26), varme.pw.oceanic-dark-theme (1.1.0), com.mallowigi.colorHighlighter (9.2.0), com.aurimasniekis.phpclasstemplates (1.0.2), ski.chrzanow.foldableprojectview (1.1.1), mobi.hsz.idea.gitignore (4.3.0), LiveTemplatePreview (0.3), com.dimabdc.idea.php.phpunit (0.5.1), org.i18nally.jetbrainsideplugin (1.1.5), fr.adrienbrault.idea.symfony2plugin (0.23.213)
```

**Comment by adelf** [comment]
I did some checks which should fix this. Thanks for posting.
