### ISSUE TITLE
[Bug]: Freeze in PHPStorm

### ISSUE THREAD

**Issue by bzixilu** [laravel-idea/plugin#871]
### Bug description

Freeze for 40 seconds
IDE KILLED! Sampled time: 30500ms, sampling rate: 100ms, GC time: 689ms (1%), Class loading: 0%

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
	at java.base@17.0.8.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
	at java.base@17.0.8.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
	at com.intellij.util.indexing.impl.MapIndexStorageSlruCache.read(MapIndexStorageCache.kt:88)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:269)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:20)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.read(TransientChangesIndexStorage.java:193)
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java:241)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getData(CompositeInvertedIndexBase.java:113)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$getContainingFilesIterator$5(FileBasedIndexEx.java:254)
	at com.intellij.util.indexing.FileBasedIndexEx$$Lambda$3487/0x00000008019da5e0.convert(Unknown Source)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:309)
	at com.intellij.util.indexing.FileBasedIndexEx$$Lambda$3053/0x000000080182d638.compute(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:309)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:251)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:227)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1056)
	at com.laravel_idea.plugin.routing.f$a.a(f$a.java:108)
	at com.laravel_idea.plugin.routing.f$a.invoke(f$a.java:107)
	at com.laravel_idea.plugin.routing.f.a(f.java:107)
	at com.laravel_idea.plugin.routing.f$$Lambda$8034/0x0000000802ab3880.process(Unknown Source)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$iterateData$1(PersistentEnumeratorBase.java:435)
	at com.intellij.util.io.PersistentEnumeratorBase$$Lambda$3357/0x000000080198a918.process(Unknown Source)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.lambda$processAll$1(AppendableStorageBackedByResizableMappedFile.java:129)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile$$Lambda$3358/0x000000080198ab68.fun(Unknown Source)
	at com.intellij.util.io.PagedFileStorage.lambda$readInputStream$1(PagedFileStorage.java:114)
	at com.intellij.util.io.PagedFileStorage$$Lambda$3359/0x000000080198afe0.execute(Unknown Source)
	at com.intellij.util.io.OpenChannelsCache.executeOp(OpenChannelsCache.java:104)
	at com.intellij.util.io.StorageLockContext.executeOp(StorageLockContext.java:108)
	at com.intellij.util.io.PagedFileStorage.executeOp(PagedFileStorage.java:140)
	at com.intellij.util.io.PagedFileStorage.readInputStream(PagedFileStorage.java:112)
	at com.intellij.util.io.ResizeableMappedFile.readInputStream(ResizeableMappedFile.java:281)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:116)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:447)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:435)
	at com.intellij.util.io.PersistentMapImpl.processKeys(PersistentMapImpl.java:556)
	at com.intellij.util.indexing.impl.ValueContainerMap.processKeys(ValueContainerMap.java:73)
	at com.intellij.util.indexing.impl.MapIndexStorage.doProcessKeys(MapIndexStorage.java:365)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:113)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:142)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:49)
	at com.intellij.util.indexing.storage.MapReduceIndexBase$$Lambda$3355/0x000000080198a250.compute(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:48)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:123)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:164)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:799)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:142)
	at com.laravel_idea.plugin.routing.f.a(f.java:107)
	at com.laravel_idea.plugin.routing.h.getNames(h.java:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:132)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:83)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:77)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.ReadActionProcessor$$Lambda$6144/0x0000000802575930.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$0(JobLauncherImpl.java:52)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$8014/0x0000000802b955b0.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:52)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$8012/0x0000000802b95360.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$6674/0x0000000802752150.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1089)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3689/0x0000000801aa9110.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1579/0x0000000800f97d10.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:89)
	at java.base@17.0.8.1/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base@17.0.8.1/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.8.1/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.8.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### Operating system

None

**Comment by adelf** [comment]
I've removed all heavy operations from traversing this index values. I hope it will help. Thank you for reporting.
