### ISSUE TITLE
[Bug]: IDE internal error

### ISSUE THREAD

**Issue by Abdelraman** [laravel-idea/plugin#892]
### Bug description

![image](https://github.com/laravel-idea/plugin/assets/4821833/4bfc4854-113d-47cc-80c9-753c155533a3)

**this error shows up constantly, with the following stack**

com.intellij.openapi.progress.IndicatorCancellationException

java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.CeProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:513)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:154)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$submit$0(PassExecutorService.java:325)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:197)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.intellij.openapi.progress.CeProcessCanceledException: com.intellij.openapi.progress.IndicatorCancellationException
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2409)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2397)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$5(context.kt:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:972)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:108)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:78)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:2397)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:2336)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1057)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:988)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.updateAndShowResult(UpdateChecker.kt:886)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.checkForUpdate(UpdateChecker.kt:550)
	at com.intellij.diagnostic.DefaultIdeaErrorLogger.canHandle(DefaultIdeaErrorLogger.java:35)
	at com.intellij.diagnostic.DialogAppender.queueAppend(DialogAppender.java:83)
	at com.intellij.diagnostic.DialogAppender.publish(DialogAppender.java:58)
	at java.logging/java.util.logging.Logger.log(Logger.java:980)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1007)
	at java.logging/java.util.logging.Logger.log(Logger.java:1118)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:169)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	... 5 more
Caused by: com.intellij.openapi.progress.IndicatorCancellationException
	at com.intellij.openapi.progress.ContextKt$cancelWithIndicator$1.invokeSuspend(context.kt:146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.openapi.progress.ProcessCanceledException: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocTypeImpl #PHP  because: containing file is null; hierarchy=class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocPropertyTagImpl, class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocCommentImpl, class com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl, context=null, contextFile=null
invalidated at: see attachment
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
	at com.intellij.codeInsight.daemon.impl.DaemonProgressIndicator.checkCanceled(DaemonProgressIndicator.java:97)
	at com.intellij.openapi.progress.ContextKt$cancelWithIndicator$1.invokeSuspend(context.kt:142)
	... 8 more
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocTypeImpl #PHP  because: containing file is null; hierarchy=class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocPropertyTagImpl, class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocCommentImpl, class com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl, context=null, contextFile=null
invalidated at: see attachment
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:212)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:31)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocTypeImpl.getType(PhpDocTypeImpl.java:331)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocTagImpl.getTypeFromDeclaration(PhpDocTagImpl.java:99)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocTagImpl.getTypeFromAst(PhpDocTagImpl.java:87)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocTagImpl.getType(PhpDocTagImpl.java:82)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.add(PhpType.java:559)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocPropertyImpl.getType(PhpDocPropertyImpl.java:88)
	at com.laravel_idea.plugin.eloquent.meta.relation.EloquentRelation.e(EloquentRelation.kt:20)
	at com.laravel_idea.plugin.eloquent.meta.relation.EloquentRelation.classInfo(EloquentRelation.kt:36)
	at com.laravel_idea.plugin.eloquent.EloquentInfo.getRelationsEloquentInfo(EloquentInfo.kt:164)
	at com.laravel_idea.plugin.eloquent.references.c.e(c.java:38)
	at com.laravel_idea.plugin.eloquent.references.c.resolve(c.java:20)
	at com.laravel_idea.plugin.common.c.b.isReferenceTo(b.java:38)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedSymbolsCache$MyReferenceHolder.isReferenceTo(PhpUnusedSymbolsCache.java:80)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedSymbolsCache.isUsedImplicitlyOrFromCache(PhpUnusedSymbolsCache.java:56)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedGlobalSymbolsPass$UnusedElementsData.searchForCandidateReferencingFiles(PhpUnusedGlobalSymbolsPass.java:290)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedGlobalSymbolsPass.searchForUnusedSymbols(PhpUnusedGlobalSymbolsPass.java:165)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedGlobalSymbolsPass.collectUnusedSymbols(PhpUnusedGlobalSymbolsPass.java:99)
	at com.jetbrains.php.lang.inspections.deadcode.local.PhpUnusedGlobalSymbolsPass.doCollectInformation(PhpUnusedGlobalSymbolsPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### Plugin version

8.0.1.233

### Operating system

Windows

**Comment by adelf** [comment]
Could you try to main menu > File > Invalidate Caches... ? It doesn't look like Laravel Idea issue.

**Comment by Abdelraman** [comment]
Yes it seems so, I did Invalidate caches and restart and it didn't show up till now, Thanks
